name: CI

on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw clean install