name: Docker Build CI
on:
  push:
    branches: [ main ]
    tags:
        - 'v*.*.*'
env:
  DOCKER_IMAGE: 'thuongbignose/project'
  JAVA_VERSION: '21'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
    
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Build with Maven
        id: build
        run: ./mvnw clean install

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
    
      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
            images: ${{ env.DOCKER_IMAGE }}
            tags: |
                type=ref,event=branch
                type=sha
                type=semver,pattern={{version}}
                type=raw,template={{version}}
            flavor: latest

      - name: Build Docker and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:cache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:cache,mode=max
          platforms: linux/amd64,linux/arm64

      - name: Image digest
        run: echo ${{ steps.build.outputs.digest }}